config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :treehouses, only: [ :index, :show, :create, :new ] do
    resources :journeys, only: :create
  end
  resources :journeys, only: :index do
    member do
      get "validate", to: "journeys#validate"
    end
  end
  root to: 'pages#home'

  # patch "journeys/:id", to: "journeys#validate"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :treehouse


  def self.hostings(user)
    owner_treehouses = Treehouse.where(user: user)
    hostings = []
    Journey.all.each do |journey|
      hostings << journey if journey.treehouse.user == user
    end
    return hostings
  end

  def total_price
    diff_days = Date.parse(self.checkout).mjd - Date.parse(self.checkin).mjd
    self.treehouse.price_per_night * diff_days
  end
end

app/models/treehouse.rb
class Treehouse < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :location, presence: true
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
  validates :capacity, presence: true, inclusion: { in: [1, 2, 3, 4] }

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController

  def index
    @journeys = policy_scope(Journey).order(created_at: :desc)
  end

  def create
    @journey = Journey.new(journey_params)
    @journey.treehouse = Treehouse.find(params[:treehouse_id])
    @journey.user_id = current_user.id
    authorize @journey
    if @journey.save
      redirect_to journeys_path
    else
      render "treehouses#show"
    end
  end

  def validate
    journey = Journey.find(params[:id])
    authorize journey
    journey.is_confirmed = params[:status] == "accepted" ? true : false
    journey.save
    redirect_to journeys_path
  end

  private

  def journey_params
    params.require(:journey).permit(:checkin, :checkout, :guests_number, :is_confirmed, :treehouse_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home

  def home
  end
end

app/controllers/treehouses_controller.rb
class TreehousesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized, only: :show

  def index
    if params[:treehouses]
      @search_params = {
        treehouse_category: params[:treehouses][:category],
        treehouse_location: params[:treehouses][:location],
        treehouse_checkin: params[:treehouses][:checkin].first,
        treehouse_checkout: params[:treehouses][:checkout].first,
        treehouse_guests_number: params[:treehouses][:guests_number],
        treehouse_price_per_night: params[:treehouses][:price_per_night]
      }
      if @search_params[:treehouse_location].blank?
        @treehouses = Treehouse.all
      elsif @search_params[:treehouse_category].blank?
        guests_number =  params[:treehouses][:guests_number].blank? ? 0 : params[:treehouses][:guests_number]
        @treehouses = Treehouse.where("capacity >= ?", guests_number)
        @treehouses = @treehouses.near(@search_params[:treehouse_location], 100)
      else
        guests_number =  params[:treehouses][:guests_number].blank? ? 0 : params[:treehouses][:guests_number]
        category_param = @search_params[:treehouse_category]
        @treehouses = Treehouse.where(
          "capacity >= :guests_number AND category ILIKE :category",
          guests_number: guests_number,
          category: "%#{category_param}%"
        )
        @treehouses = @treehouses.near(@search_params[:treehouse_location], 100)
      end
    else
      @treehouses = Treehouse.all
      @search_params = {}
    end
    treehouses_flags = @treehouses.where.not(latitude: nil, longitude: nil)

    @markers = treehouses_flags.map do |treehouse|
      @treehouse_for_view = treehouse
      {
        lat: treehouse.latitude,
        lng: treehouse.longitude,
        icon: "https://res.cloudinary.com/dqwxvdtnv/image/upload/v1512067586/yus79fy3kdontkwneo1y.png",
        infoWindow: { content: render_to_string(partial: "/treehouses/map_box", locals: { treehouse: @treehouse_for_view }) }
      }
    end
  end

  def new
    @treehouse = Treehouse.new
    authorize @treehouse
  end

  def create
    @treehouse = Treehouse.new(treehouse_params)
    @treehouse.user = current_user
    authorize @treehouse
    if @treehouse.save
      redirect_to treehouse_path(@treehouse)
    else
      render :new
    end
  end

  def show
    @treehouse = Treehouse.find(params[:id])
    @journey = Journey.new
  end

  private

  def treehouse_params
    params.require(:treehouse).permit(:title, :capacity, :description, :location, :price_per_night, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/journeys/index.html.erb
<div class="container">

  <div class="invite">
    <div class="invite-content">
      <i class="fa fa-eur" aria-hidden="true"></i>
    <h3><em>Earn 50€ credit trip!</em></h3>
    <p>Share with your friends the Treehouse code: <strong>TH<%= @current_user.email.split("@")[0].capitalize %><%= @current_user.id %></strong></p>
    <%= link_to ' Share on <i class="fa fa-facebook" aria-hidden="true"></i>'.html_safe, 'https://www.facebook.com/', class: "btn greenbtn btn-primary", target:"_blank" %>
    </div>
  </div>

<div class="dash-title">
   <h2><%= @current_user.email.split("@")[0].capitalize %>'s Dashboard</h2>
</div>


  <div class="tabs">
    <a href="#" class="guest tab tab-guest active">I'm Traveling</a>
    <a href="#" class="host tab tab-host">I'm Hosting</a>
  </div>

  <div class="row">
    <div class="inbox-guest" id="guest">
      <ul class="inbox">
        <% @journeys.each do |journey| %>
        <li class="message">
          <!-- Code your message here -->
          <img src="https://kitt.lewagon.com/placeholder/users/lionel-k" class="avatar_sm">
          <div class="message_name">
            <h2><strong><%= journey.treehouse.user.email.split("@")[0].capitalize %></strong></h2>
            <h2><%= journey.treehouse.location %></h2>
          </div>
          <div class="dates">
            <h4>Check-In - Check-Out</h4>
            <p><%= journey.checkin %>   -   <%= journey.checkout %></p>
          </div>
          <div class="guests">
            <h4>Guests number</h4>
            <p><center><%= journey.guests_number %></center></p>
          </div>
          <div class="message_status text_greylight">
            <h4 class="status text_greylight">
              <% if journey.is_confirmed %>
              <div class="accepted"><%= "Accepted" %></div>
              <% else %>
              <div class="declined"><%= "Pending" %></div>
              <% end %>
            </h4>
            <h4 class="price"><%= journey.total_price %>€</h4>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="inbox-host" id="host">
      <ul class="inbox">
        <% my_hostings = Journey.hostings(current_user) %>
        <% my_hostings.each do |journey| %>
        <li class="message">
          <!-- <img src="https://kitt.lewagon.com/placeholder/users/lionel-k" class="avatar_sm"> -->
          <div class="message_name">
            <h2></h2>
            <h2><strong><%= journey.user.email.split("@")[0].capitalize %></strong></h2>
          </div>

          <div class="dates">
            <h4>Check-In - Check-Out</h4>
            <p><%= journey.checkin %>   -   <%= journey.checkout %></p>
          </div>

          <div class="guests">
            <h4>Guests number</h4>
            <p><center><%= journey.guests_number %></center></p>
          </div>

          <div class="message_status text_greylight">
            <h4 class="status text_greylight">
              <% if journey.is_confirmed %>
              <div class="accepted"><%= "Accepted" %></div>
              <% else %>
              <div class="declined"><%= "Pending" %></div>
              <% end %>
            </h4>

            <h4 class="price"><%= journey.total_price %>€</h4>
          </div>

          <div class="message_body">
            <%= link_to "Accept!", validate_journey_path(journey, status: 'accepted'), class: "btn greenbtn btn-success" %>
            <p></p>
            <%= link_to "Decline", validate_journey_path(journey, status: 'declined'), class: "btn btn-danger" %>
          </div>

        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= favicon_link_tag 'logo.png' %>
  <title>TreeHouse</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render "shared/navbar" %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render "shared/footer" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag "map" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner image-banner">
  <div class="banner-content">
    <h1>TreeHouse</h1>
    <p><span id="banner-typed-text"></span></p>
    <!-- <p>Find a place to chill</p> -->
    <%= render "shared/form" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    App made with <i class="fa fa-heart"></i> during the AirBnB Week @ Le Wagon Coding Bootcamp
  </div>
</div>

app/views/shared/_form.html.erb
<%= form_tag treehouses_path, method: :get, class: 'form-inline' do %>

  <%= text_field_tag 'treehouses[location]', nil, class: "form-control text-center", id: 'treehouse_location', placeholder: "Choose destination", autofocus: true %>

  <%= date_field 'treehouses[checkin]', nil, class: "form-control datepicker text-center date-input", placeholder: "Checkin" %>

  <%= date_field 'treehouses[checkout]', nil, class: "form-control datepicker text-center date-input", placeholder: "Checkout" %>

  <%= select_tag 'treehouses[guests_number]', options_for_select([['1'], ['2'], ['3'], ['4']]), class: "form-control text-center unselected", id: 'guest', prompt: "Guests" %>

  <%= submit_tag "Search", class: "btn home-btn" %>
<% end %>

app/views/shared/_form_index.html.erb
<%= form_tag treehouses_path, method: :get, class: 'form-inline results-filter' do %>

  <% location = params[:treehouses][:location] if params[:treehouses] %>
  <%= label_tag 'treehouses[location]', 'Stay in', class: "label-form-name" %>
  <%= text_field_tag 'treehouses[location]', nil, class: "form-control label-form-input large text-center", id: 'treehouse_location', placeholder: "Destination", value: location %>

  <% checkin = params[:treehouses][:checkin] if params[:treehouses] %>
  <%= label_tag 'treehouses[checkin]', 'from', class: "label-form-name" %>
  <%= date_field 'treehouses[checkin]', nil, class: "form-control datepicker text-center label-form-input medium", placeholder: "Checkin", value: checkin %>

  <% checkout = params[:treehouses][:checkout] if params[:treehouses]%>
  <%= label_tag 'treehouses[checkout]', 'to', class: "label-form-name" %>
  <%= date_field 'treehouses[checkout]', nil, class: "form-control datepicker text-center label-form-input medium", placeholder: "Checkout", value: checkout %>

  <% guests_number = params[:treehouses][:guests_number] if params[:treehouses] %>
  <%= label_tag 'treehouses[guests_number]', 'for', class: "label-form-name" %>
  <%= select_tag 'treehouses[guests_number]', options_for_select([['1'], ['2'], ['3'], ['4']], guests_number), class: "form-control text-center label-form-input small unselected", prompt: "Guests" %>

  <%= submit_tag "Refresh", class: "btn refresh-btn" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", id:"clickme", data: {sound_url: asset_path('sound.mp3')} %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Post your offer", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Journeys", journeys_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "default-user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <strong><%= current_user.email.split("@")[0].capitalize %></strong>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/journeys/index.html.erb
<div class="container">

      <h1>YMy Dashboard</h1>

      <!-- Code your tabs here -->

      <div class="tabs">
        <a href="#" class="tab active">Traveling</a>
        <a href="#" class="tab">Hosting</a>
      </div>

      <ul class="inbox">
        <li class="message">
          <!-- Code your message here -->
          <img src="../images/gab.png" class="avatar_sm">
          <div class="message_name">
            <h2>Gab Dehan</h2>
            <p>10/07/17</p>
          </div>
          <div class="message_body">
            <h4><strong>I am not sure yet!</strong></h4>
            <p>I am not sure yet! I might be in Shanghai at this moment... Can I tell you later?</p>
          </div>
          <div class="message_status text_greylight">
            <h2 class="status text_greylight">Pending</h2>
            <h2 class="price">€345</h2>
          </div>
        </li>
        <li class="message">
          <!-- Code your message here -->
          <img src="../images/cecile.png" class="avatar_sm">
          <div class="message_name">
            <h2>Cecile Veneziani</h2>
            <p>23/09/17</p>
          </div>
          <div class="message_body">
            <h4><strong>I’ll be glad to welcome you in my cosy flat</strong></h4>
            <p>I’ll be glad to welcome you in my cosy flat in Lille. When are you arriving exactly?</p>
          </div>
          <div class="message_status text_green">
            <h2 class="status">Accepted</h2>
            <h2 class="price">€345</h2>
          </div>
        </li>
        <li class="message">
          <!-- Code your message here -->
          <img src="../images/jad.png" class="avatar_sm">
          <div class="message_name">
            <h2>Jad Joubran</h2>
            <p>19/08/17</p>
          </div>
          <div class="message_body">
            <h4><strong>Hey man! I'm sorry...</strong></h4>
            <p>Hey man! I'm sorry... I'll be in Amsterdam at these dates.</p>
          </div>
          <div class="message_status text_red">
            <h2 class="status">Declined</h2>
            <h2 class="price">€560</h2>
          </div>
        </li>
      </ul>

    </div>

app/views/treehouses/_map_box.html.erb
<h4><strong><%= treehouse.title %></strong></h4>
<p><span class="light-words">from </span><%= treehouse.price_per_night %>€/night</p>

<div class="results-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @treehouse_for_view.photo, height: 150, width: 200, crop: :fill if @treehouse_for_view.photo.present? %>');">
</div>

app/views/treehouses/index.html.erb
<div class="results-wrapper">


  <div class="main-results-container">
    <div class="results-container text-center">

      <h3>Our selection of treehouses</h3>
      <div class="filters-bar text-center">
        <%= render "shared/form_index" %>
        <div class="categories-container">

          <% ['lake', 'family', 'romantic', 'woods', 'mountains', 'fields'].each do |category| %>
            <%= link_to treehouses_path(params.to_unsafe_h.merge(:treehouses => {
              category: category,
              location: params[:treehouses][:location],
              checkin: params[:treehouses][:checkin],
              checkout: params[:treehouses][:checkout],
              guests_number: params[:treehouses][:guests_number]
            })) do %>
            <div class="category-item tag <%= category %>">
              <%= image_tag "#{category}-icon.png", class: "img-icon" %>
              <h5><%= category.capitalize %></h5>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <p class="text-left"><%= @treehouses.length < 2 ? "#{ @treehouses.length } result" : "#{ @treehouses.length } results" %></p>

      <div class="results-cards">
        <% @treehouses.each do |treehouse| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to treehouse_path(@search_params.merge(id: treehouse.id)) do %>
          <div class="results-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path treehouse.photo, height: 300, width: 400, crop: :fill if treehouse.photo.present? %>');">
          </div>
          <div class="results-detail">
            <h4><%= treehouse.title %></h4>
            <p><span class="light-words">from </span><%= treehouse.price_per_night %>€/night</p>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>

    </div>

    <div id="map" data-markers="<%= @markers.to_json %>"></div>

  </div>

</div>

app/views/treehouses/new.html.erb
<div class="banner-host image-banner">
  <div class="container">

    <div class="banner-content-host">

      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="formulaire">


<!--           <h2 class="text-center">My Offer</h2> -->
          <%= simple_form_for @treehouse, :html => { class: 'form-checkox-inline' } do |f| %>
            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :location, id: "treehouse_location" %>
            <%= f.label :category %>
            <%= f.input :category,
                :as => :check_boxes,
                :collection => ["Lake", "Family", "Romantic", "Woods", "Mountains", "Fields"],
                label: false
            %>
            <%= f.input :price_per_night, :label => "Price Per Night (€)" %>
            <%= f.input :capacity, collection: [ 1 ,2 ,3, 4 ], :label => "Capacity (Between 1 and 4)" %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit "Create!", class: "btn btn-primary form-control" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/treehouses/show.html.erb
<div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @treehouse.photo if @treehouse.photo.present? %>');">
  <h1><%= @treehouse.title %></h1>
</div>
<!-- content -->

<div class="main-container">
  <div class="treehouse-details">
    <h3>Categories</h3>

    <div class="categories-container">

      <% @treehouse.category.split.each do |category| %>

      <div class="category-item tag <%= category %>">
        <% image_link = "#{category}-icon.png" %>
        <%= image_tag image_link, class: "img-icon" %>
        <h5><%= category.capitalize %></h5>
      </div>
      <% end %>

    </div>

    <hr>

    <h3>Description</h3>
    <%= @treehouse.description %>
  </div>


  <% unless @treehouse.user == current_user %>
  <div class="journey-request">

    <!-- bid part -->
    <div class="bidding-part text-center">
      <div class="price">
        <p id="price_per_night"><%= @treehouse.price_per_night%>€ per night</p>
      </div>

      <%= simple_form_for @journey, :url => treehouse_journeys_path(@treehouse), :method => :post, html: {class: 'form-inline custom-select2'} do |f| %>
      <div class= "form-show-date-wrapper">
        <label class="label-show"><span>Start date</span></label>
        <% start_date = Date.parse(params["treehouse_checkin"]) unless params["treehouse_checkin"].blank? %>
        <%= f.input :checkin, as: :string, required: false, input_html: { id: "range_start", class: "form-show-date", class: "datepicker text-center white", value: start_date }, label: false, placeholder: "CheckIn" %>
      </div>
      <div class= "form-show-date-wrapper">
        <label class="label-show"><span>End date</span></label>
        <% end_date = Date.parse(params["treehouse_checkout"]) unless params["treehouse_checkout"].blank? %>
        <%= f.input :checkout, as: :string, required: false, input_html: { id: "range_end", class: "form-show-date", class: "datepicker text-center white", value: end_date }, label: false, placeholder: "CheckOut" %>
      </div>
      <div class= "form-show-date-wrapper">
        <label class="label-show text-center"><span>Guests</span></label>
        <%= f.input :guests_number, :collection => [1, 2, 3, 4], label: false, prompt: "Guests", selected: params["treehouse_guests_number"], input_html: { style: "width: 50px", class: "text-center" } %>
      </div>

      <br>
      <div id="total_price">
      </div>
      <div class= "form-show-button-wrapper">
        <%= f.button :submit, "Reservation Request", class: "btn form-show-button" %>
      </div>
      <% end %>
    </div>
    <!-- fin input bid -->
    <% end %>
  </div>



</div>

<div id="map" data-markers="<%= @markers.to_json %>"></div>